name: Nate's Site
title: Nate's Page
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
description: Nate's first github page.
